### ISSUE TITLE
tracking down some errors in logs

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1385]
### Stacktraces

<details><summary>(solved) this bug was temporary due to other mod which is now fixed</summary>

Not sure if this is due to recent changes to LSM, or due to PR #1381 :

```
Simulation error: Object reference not set to an instance of an object
at (wrapper dynamic-method) Vehicle.Vehicle.Spawn_Patch1 (Vehicle&,uint16) <0x0056a>
at CarAI.TrySpawn (uint16,Vehicle&) <0x000c8>
at TrafficManager.Patch._VehicleAI._CarAI.SimulationStepPatch.Prefix (CarAI,uint16,Vehicle&,UnityEngine.Vector3) <0x002cc>
at (wrapper dynamic-method) CarAI.CarAI.SimulationStep_Patch1 (CarAI,uint16,Vehicle&,UnityEngine.Vector3) <0x00057>
at (wrapper dynamic-method) CargoTruckAI.CargoTruckAI.SimulationStep_Patch0 (CargoTruckAI,uint16,Vehicle&,UnityEngine.Vector3) <0x00177>
at VehicleManager.SimulationStepImpl (int) <0x00511>
at SimulationManagerBase`2.SimulationStep (int) <0x0004c>
at VehicleManager.ISimulationManager.SimulationStep (int) <0x00024>
at SimulationManager.SimulationStep () <0x00693>
at SimulationManager.SimulationThread () <0x0018a>
  [Core]
```

</details>

Also getting a few of these ~~(but possibly due to Building Spawn Points mod)~~:

```
Vehicle not found!
   at System.Environment.get_StackTrace()
   at Building.RemoveOwnVehicle(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.RemoveSource(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.ArriveAtSource(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.ArriveAtDestination(UInt16 vehicleID, Vehicle ByRef vehicleData)
   at CarAI.CarAI.SimulationStep_Patch0(.CarAI , UInt16 , Vehicle ByRef , Frame ByRef , UInt16 , Vehicle ByRef , Int32 )
   at FireTruckAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, Frame ByRef frameData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at VehicleAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at TrafficManager.Patch._VehicleAI._CarAI.SimulationStepPatch.Prefix(.CarAI __instance, UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at CarAI.CarAI.SimulationStep_Patch1(.CarAI , UInt16 , Vehicle ByRef , Vector3 )
   at FireTruckAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at VehicleManager.SimulationStepImpl(Int32 subStep)
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at VehicleManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]
```

### Logs

* [output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/8038043/output_log.txt)
* [TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/8038045/TMPE.log)

**Comment by krzychu124** [comment]
Did you use [Smarter Firefighters: Improved AI](https://steamcommunity.com/sharedfiles/filedetails/?id=2346565561) before? Errors about `vehicle not found` + `FireTruckAI` in the stacktrace are almost always caused by that mod or because of unsubscribing it (incorrect allocation of guest/own vehicles might throw warning/error even if you remove the mod).

**Comment by aubergine10** [comment]
No, never used that mod (although been considering it as vanilla fire fighter AI is pants). The fire truck stuff has been happening for quite some time and it seems related to this: https://github.com/MacSergey/BuildingSpawnPoints/issues/28 

I'm going to try running with 11.6.4.7 build for a few hours and see what happens to the `TrySpawn` null ref. If it's still happening then it's likely something that changed in past couple of days (ie. not TM:PE).

**Comment by krzychu124** [comment]
#1381 has nothing to the error you showed. `Vehicle not found!` means that either vehicle was not added correctly to the building once spawned or something happened to the building which caused a desync -> vehicle has not been found in the list of vehicles connected with that building (guest and own vehicles are used when you click on the building to show incoming or spawned vehicles) - it shouldn't break anything from simulation perspective

**Comment by aubergine10** [comment]
I'm no longer getting the null ref at `CarAI.TrySpawn` - only thing that's changed (forgot to rebuild mod) is some mods/assets updated as below:

![image](https://user-images.githubusercontent.com/1386719/153532897-47098db6-57b5-42ac-8ee2-acc408d9580d.png)

But now getting this error:

```
Invalid list detected!
   at System.Environment.get_StackTrace()
   at CarAI.CarAI.CheckOtherVehicles_Patch1(UInt16 , Vehicle ByRef , Frame ByRef , Single ByRef , Boolean ByRef , Vector3 ByRef , Single , Single , Int32 )
   at CarAI.CarAI.SimulationStep_Patch0(.CarAI , UInt16 , Vehicle ByRef , Frame ByRef , UInt16 , Vehicle ByRef , Int32 )
   at VehicleAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at TrafficManager.Patch._VehicleAI._CarAI.SimulationStepPatch.Prefix(.CarAI __instance, UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at CarAI.CarAI.SimulationStep_Patch1(.CarAI , UInt16 , Vehicle ByRef , Vector3 )
   at CargoTruckAI.CargoTruckAI.SimulationStep_Patch0(.CargoTruckAI , UInt16 , Vehicle ByRef , Vector3 )
   at VehicleManager.SimulationStepImpl(Int32 subStep)
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at VehicleManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]
```

Also getting this with disaster vehicles:

```
Vehicle not found!
   at System.Environment.get_StackTrace()
   at Building.RemoveOwnVehicle(UInt16 vehicleID, Vehicle ByRef data)
   at DisasterResponseVehicleAI.RemoveSource(UInt16 vehicleID, Vehicle ByRef data)
   at DisasterResponseVehicleAI.ArriveAtSource(UInt16 vehicleID, Vehicle ByRef data)
   at DisasterResponseVehicleAI.ArriveAtDestination(UInt16 vehicleID, Vehicle ByRef vehicleData)
   at CarAI.CarAI.SimulationStep_Patch0(.CarAI , UInt16 , Vehicle ByRef , Frame ByRef , UInt16 , Vehicle ByRef , Int32 )
   at DisasterResponseVehicleAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, Frame ByRef frameData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at VehicleAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at TrafficManager.Patch._VehicleAI._CarAI.SimulationStepPatch.Prefix(.CarAI __instance, UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at CarAI.CarAI.SimulationStep_Patch1(.CarAI , UInt16 , Vehicle ByRef , Vector3 )
   at DisasterResponseVehicleAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at VehicleManager.SimulationStepImpl(Int32 subStep)
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at VehicleManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]
```

Going to try again tomorrow but without service vehicle selector see if that has any effect.

**Comment by krzychu124** [comment]
Any conclusions? Have you had a change to test it?

**Comment by krzychu124** [comment]
Reopen if issue persist.
