### ISSUE TITLE
`Reversible Tram AI` patch failed

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1470]
I had Reversible Tram AI mod subscribed but not enabled. Built using current `master` branch **TM:PE 11.6.5.1**.

```batch
Error 479.5659164: HarmonyLib.HarmonyException: Patching exception in method static System.Boolean ReversibleTramAI.SimulationStepPatch1::Prefix(VehicleAI __instance, System.UInt16 vehicleID, Vehicle& data, UnityEngine.Vector3 physicsLodRefPos, VehicleInfo& ___m_info) 
   ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Could not find TrySpawn call or instructions has been patched
  at TrafficManager.Patch._External._RTramAIModPatch.RTramAIModPatch.Transpiler (System.Reflection.Emit.ILGenerator il, IEnumerable`1 instructions) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at HarmonyLib.CodeTranspiler+<>c__DisplayClass12_0.<GetResult>b__0 (System.Reflection.MethodInfo transpiler) [0x00000] in <filename unknown>:0 
  at System.Collections.Generic.List`1[System.Reflection.MethodInfo].ForEach (System.Action`1 action) [0x00000] in <filename unknown>:0 
  at HarmonyLib.CodeTranspiler.GetResult (System.Reflection.Emit.ILGenerator generator, System.Reflection.MethodBase method) [0x00000] in <filename unknown>:0 
  at HarmonyLib.MethodBodyReader.FinalizeILCodes (HarmonyLib.Emitter emitter, System.Collections.Generic.List`1 transpilers, System.Collections.Generic.List`1 endLabels, System.Boolean& hasReturnCode) [0x00000] in <filename unknown>:0 
  at HarmonyLib.MethodCopier.Finalize (HarmonyLib.Emitter emitter, System.Collections.Generic.List`1 endLabels, System.Boolean& hasReturnCode) [0x00000] in <filename unknown>:0 
  at HarmonyLib.MethodPatcher.CreateReplacement (System.Collections.Generic.Dictionary`2& finalInstructions) [0x00000] in <filename unknown>:0 
  at HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) [0x00000] in <filename unknown>:0 
  at HarmonyLib.PatchClassProcessor.ProcessPatchJob (HarmonyLib.Job job) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) [0x00000] in <filename unknown>:0 
  at HarmonyLib.PatchClassProcessor.ProcessPatchJob (HarmonyLib.Job job) [0x00000] in <filename unknown>:0 
  at HarmonyLib.PatchClassProcessor.BulkPatch (System.Collections.Generic.List`1 originals, System.Reflection.MethodBase& lastOriginal) [0x00000] in <filename unknown>:0 
  at HarmonyLib.PatchClassProcessor.Patch () [0x00000] in <filename unknown>:0 
	====================
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Error(System.String s)
   at TrafficManager.Util.Shortcuts.LogException(System.Exception ex, Boolean showInPanel)
   at TrafficManager.Lifecycle.Patcher.PatchAll(System.String harmonyId, System.Type required, System.Type forbidden)
   at TrafficManager.Lifecycle.Patcher.Install()
   at TrafficManager.Lifecycle.TMPELifecycle.Load()
   at TrafficManager.Lifecycle.TrafficManagerMod.OnLevelLoaded(LoadMode mode)
   at LoadingWrapper.LoadingWrapper.OnLevelLoaded_Patch10(.LoadingWrapper , UpdateMode )
   at LoadingManager+<LoadLevelComplete>c__Iterator9.LoadingManager+<LoadLevelComplete>c__Iterator9.MoveNext_Patch1(.<LoadLevelComplete>c__Iterator9 )
   at LoadingManager.FpsBoosterUpdate()
   at BehaviourUpdater.Updater.Update()
```

Logs:
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/8264845/TMPE.log)
[output_log.zip](https://github.com/CitiesSkylinesMods/TMPE/files/8264874/output_log.zip)

**Comment by krzychu124** [comment]
#1457 there was a check for enabled mod, now it is not checking @kianzarrin

**Comment by kianzarrin** [comment]
related to #1457
