### ISSUE TITLE
Null ref errors in master

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1571]
@kianzarrin is this something to do with recent changes making Adaptive Networks incompatible?

```
1,057,848ms | AdaptiveRoads | 
[Exception] 1,057,848ms | node=NetNodeExt(25299 flags=HC_Mod, HUT_Mod, TwoSegments, SamePrefab) -> 
System.NullReferenceException: Object reference not set to an instance of an object
  at TrafficManager.Manager.Impl.LaneConnection.LaneConnectionSubManager.HasNodeConnections (UInt16 nodeId) [0x00000] in <filename unknown>:0 
  at TrafficManager.Manager.Impl.LaneConnection.LaneConnectionManager.HasNodeConnections (UInt16 nodeId) [0x00000] in <filename unknown>:0 
  at AdaptiveRoads.Manager.NetNodeExt.UpdateFlags () [0x00000] in <filename unknown>:0 
	-- end of exception --
   at KianCommons.Log.Exception(System.Exception ex, System.String m, Boolean showInPanel)
   at KianCommons.LogExtensions.Log(System.Exception ex, System.String message, Boolean showInPannel)
   at AdaptiveRoads.Manager.NetNodeExt.UpdateFlags()
   at AdaptiveRoads.Manager.NetworkExtensionManager.UpdateAllNetworkFlags()
   at AdaptiveRoads.Manager.NetworkExtensionManager.LoadImpl()
   at AsyncAction.Execute()
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()
```

**Comment by aubergine10** [comment]
[output_log.zip](https://github.com/CitiesSkylinesMods/TMPE/files/8666885/output_log.zip)
[otherlogs.zip](https://github.com/CitiesSkylinesMods/TMPE/files/8666886/otherlogs.zip)
[Logs.zip](https://github.com/CitiesSkylinesMods/TMPE/files/8666888/Logs.zip)

**Comment by kianzarrin** [comment]
HUT and DCR mods that are now in WS are incompatible with TMPE master. krzychu did not agree to do a API hotfix so we have to deal with the confusion. Maybe the errors in DCR and HUT stopped TMPE from loading properly because I cannot find this line in your log:
```
OnLevelLoading: JunctionRestrictionsManager
```

I have been playing with TMPE+AN for a long time and did not face any problems. 

@aubergine10  if this answers your question please close the issue.
