### ISSUE TITLE
CSM mod support

### ISSUE THREAD

**Issue by sidboy55555** [CitiesSkylinesMods/TMPE#1654]
### Describe your idea
Since version 2209.211 of the Cities Skylines multiplayer mod (CSM), they have added a modding api for other modders to add support for their mod in CSM. It would be nice if there would be full compatibility between TM:PE and CSM

### Screenshots?

No, just a link to the changelog/release page:
https://github.com/CitiesSkylinesMultiplayer/CSM/releases

See versin 2209.211

### Notes or questions?

It would be nice if my 2 favo mods would work better together <3

**Comment by krzychu124** [comment]
See, I didn't even enable the mod and I got the error which can cause a ton of issues. 
If they can't fix basic things then why we should bother adding support (I doubt that's even possible in that state). CSM was marked as incompatible because we don't have any functions to synchronize data across clients but most importantly because just having CSM installed(not even enabled) breaks a lot of things which never break without that mod.

Closing. I'll reopen if they fix issues. Mod **should not** throw any exceptions. It's impossible to work with it in that state.


![image](https://user-images.githubusercontent.com/19638970/192123302-d77d90b6-aa5a-4e34-b619-b12568ab8533.png)

```cs
System.TypeLoadException: Could not load type 'System.ServiceModel.Description.IOperationBehavior' from assembly 'System.ServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'., System.TypeLoadException: Could not load type 'System.ServiceModel.Configuration.BehaviorExtensionElement' from assembly 'System.ServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'., System.TypeLoadException: Could not load type 'System.ServiceModel.Description.IEndpointBehavior' from assembly 'System.ServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'., System.TypeLoadException: Could not load type 'System.ServiceModel.Description.DataContractSerializerOperationBehavior' from assembly 'System.ServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'., System.TypeLoadException: Could not load type 'System.Runtime.Serialization.XmlObjectSerializer' from assembly 'System.Runtime.Serialization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.,  }
System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetExportedTypes () [0x00000] in <filename unknown>:0 
  at ColossalFramework.Plugins.PluginManager+PluginInfo.AddAssembly (System.Reflection.Assembly asm) [0x00000] in <filename unknown>:0 
	-- end of exception --
   at KianCommons.Log.Exception(System.Exception ex, System.String m, Boolean showInPanel)
   at LoadOrderIPatch.Patches.CMPatch.LogExceptionInLOM(System.Exception ex)
   at ColossalFramework.Plugins.PluginManager+PluginInfo.AddAssembly(System.Reflection.Assembly asm)
   at ColossalFramework.Plugins.PluginManager.LoadDependenciesRecursive(System.Reflection.Assembly asmRO, System.Collections.Generic.Dictionary`2 plugins, System.Collections.Generic.Dictionary`2 asmsRO, System.Collections.Generic.List`1 traversed)
   at ColossalFramework.Plugins.PluginManager.LoadDependenciesRecursive(System.Reflection.Assembly asmRO, System.Collections.Generic.Dictionary`2 plugins, System.Collections.Generic.Dictionary`2 asmsRO, System.Collections.Generic.List`1 traversed)
   at ColossalFramework.Plugins.PluginManager.LoadDependencies(System.Collections.Generic.Dictionary`2 plugins, System.Collections.Generic.Dictionary`2 asmsRO)
   at ColossalFramework.Plugins.PluginManager.LoadAssemblies(System.Collections.Generic.Dictionary`2 plugins)
   at ColossalFramework.Plugins.PluginManager.LoadPlugins()
   at Starter.Awake()
````

**Comment by tester256** [comment]
Hey @krzychu124 , there has been an update on CSM 2 weeks ago that fixes the exeptions it was throwing. Would you think it is possible to fix its compatibility now? I´m really looking forward to it since this is the best Mod and the possibility of conbining it with CSM would be awesome. 🤞🤞🤞🤞

**Comment by marcoboy123** [comment]
CSM Is working decently well now, been playing with a Friend and has only a few Desync Issues 🤞🤞🤞🤞

**Comment by Elexios** [comment]
> CSM Is working decently well now, been playing with a Friend and has only a few Desync Issues 🤞🤞🤞🤞
have you had many issues since leaving this comment been looking around for anyone talking about how they work together because ive beene enjoying playing csm but just cannot play cities skylines without tmpe

**Comment by marcoboy123** [comment]
> have you had many issues since leaving this comment been looking around for anyone talking about how they work together because ive beene enjoying playing csm but just cannot play cities skylines without tmpe

You cant use tmpe, it wont sync at all right now.
