### ISSUE TITLE
Hot reload of dev builds seems broken

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#762]
Tried doing a hot reload and the main menu button (crown button) stopped functioning.

[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4271228/TMPE.log)

```cs
Error 10,971.8881554: Toggle mainmenu failed System.NullReferenceException: Object reference not set to an instance of an object
  at TrafficManager.UI.MainMenu.MainMenuButton.HandleClick (ColossalFramework.UI.UIMouseEventParameter p) [0x00000] in <filename unknown>:0 
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Error(System.String s)
   at TrafficManager.UI.MainMenu.MainMenuButton.HandleClick(ColossalFramework.UI.UIMouseEventParameter p)
   at TrafficManager.U.Button.BaseUButton.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIComponent.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIInput+MouseHandler.ProcessInput(IInputTranslator translator, Ray ray, ColossalFramework.UI.UIComponent component, Boolean retainFocusSetting)
   at ColossalFramework.UI.UIInput.ProcessMouseInput()
   at ColossalFramework.UI.UIInput.Update()
```

Suspect it might be related to the UI updates from #656

**Comment by aubergine10** [comment]
Note: Both the existing and updated builds were `RELEASE LABS` - not sure if that has any effect?

**Comment by kianzarrin** [comment]
Related #730

**Comment by kianzarrin** [comment]
I have been struggling with the freaking UI for my road selection panel for a month ... this is not my strong suite! looking at the error log it does not seem hard to fix. I will have a look

**Comment by aubergine10** [comment]
@kianzarrin Is this separate issue to that fixed in #764 ?

**Comment by kianzarrin** [comment]
yes

**Comment by kianzarrin** [comment]
#1492 also fixed this.
