### ISSUE TITLE
Timed Traffic Light tool not properly cleaned up on close

### ISSUE THREAD

**Issue by krzychu124** [CitiesSkylinesMods/TMPE#861]
### Describe the problem
Timed Traffic lights UI breaks when user closing UI or selecting other tool without unselecting node first.

### Steps to reproduce

1. Set up simple TTL at any intersection you want
2. You can start TTL sequence but not required
3. Hit close tool (Esc) or change tool to other one
4. Enable TTL tool again (breaks UI - screenshot below)

### Log files

```cs
Error 851.9354609: TimedTrafficLightsTool._guiTimedControlPanel: System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
  at System.Collections.Generic.List`1[System.UInt16].get_Item (Int32 index) [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.SubTools.TimedTrafficLights.TimedTrafficLightsTool.GuiTimedControlPanel (Int32 num) [0x00000] in <filename unknown>:0 
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Error(System.String s)
   at TrafficManager.UI.SubTools.TimedTrafficLights.TimedTrafficLightsTool.GuiTimedControlPanel(Int32 num)
   at UnityEngine.GUILayout+LayoutedWindow.DoWindow(Int32 windowID)
   at UnityEngine.GUI.CallWindowDelegate(UnityEngine.WindowFunction func, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
```

### Savegame?
Not necessary, UI always breaks 

### Screenshots?

![image](https://user-images.githubusercontent.com/19638970/80159149-94873b80-85ca-11ea-9665-e305b3b50bd6.png)

### Notes
Tested on **TM:PE 11.4.0:FullDebug-master**, works on **11.2.x** 

When UI became broken, **RightClick** anywhere to reset internal node selection then all should start work correctly

**Comment by krzychu124** [comment]
It's not cleanup issue, but one of last menu/UI refactoring process introduced a little bug.
Previously default action when user activated **Timed Traffic Lights** tool was setting subTool **mode** to:  `TimedTrafficSelectNode`. 
During refactoring, Traffic Lights specific `subTool` modes were extracted to internal `TTLToolMode`. 
Now during initialization of TTL tool, `SelectTool` is set, but not each time when user activates tool, which is causing above issues misinterpreted as improper cleanup on tool deactivation. 

Possible quick fix: add code to set internal `TTLToolMode` to `SelectNode` each time tool is activating
